//Streams for input/output
#include <fstream>
#include <sstream>
#include <iostream>

//Datatypes
#include <vector> 
#include <string>

//Global variables for saving the sequences of A, b and coefficients generated by the elimination
std::vector<std::vector<std::vector<double>>> As {};
std::vector<std::vector<double>> bs {};
std::vector<std::vector<std::vector<double>>> Coeffs {};

/*
Converts a matrix (vector of vectors of doubles) into a String
*/
std::string to_str(std::vector<std::vector<double>> A)
{
	std::string result {};	
	for (int i=0; i<A.size(); i++){
		for (int j=0; j<A.at(i).size(); j++){
			result += std::to_string(A.at(i).at(j));
			result += " ";
		}
		result += "\n";
	}
	return result;
}
/*
Converts a vector of doubles into a String
*/
std::string to_str(std::vector<double> b)
{
	std::string result {};	
	for (int i=0; i<b.size(); i++){
		result += std::to_string(b.at(i));
		result += " ";
	}
	return result;
}

/*
Reads in a file in the format specified in the exercise,
writes matrix A and vector b as first entries to the global variables As and bs.
Returns an integer SUCCESS.
*/
int read_LP(std::string filename)
{
	std::ifstream infile(filename);
	std::string line;
	
	if (!infile){
	std::cerr << "Could not read file "+filename;
	return EXIT_FAILURE;
	}

	std::getline(infile, line);
	std::istringstream iss(line);
	int m, n;
	iss >> m >> n;

	std::getline(infile, line); //ToDo: maybe omit the following lines because c is not used
	iss.str (line);
	iss.clear();
	std::vector<double> c;
	double d;
	while(iss >> d)	c.push_back(d);

	std::getline(infile, line);
	iss.str (line);
	iss.clear();
	std::vector<double> b;
	while(iss >> d) b.push_back(d);

	std::vector<std::vector<double>> A;
	while (std::getline(infile, line)){
		iss.str (line);
		iss.clear();
		std::vector<double> a;
		while(iss >> d) a.push_back(d);
		A.push_back(a);	
	}
	//ToDo: verify that A is indeed an mxn-matrix

	bs.push_back(b);
	As.push_back(A);
	return EXIT_SUCCESS;
}

/*
Applies one Fourier-Motzkin-elemination step to the last Elements of As and bs
(in order to eliminate the first variable of the system Ax <= b)
and writes the result as new last elements of As and bs,
stores the coefficients used to generate the new inequalities as last element of Coeffs
*/
void fourier_motzkin_step()
{
	//Compute index sets U, L, N for upper bounds/lower bounds/first variable not used
	std::vector<int> U {};
	std::vector<int> L {};
	std::vector<int> N {};
	for (int i=0; i<A.size(); i++) {
		if (A.at(i).at(0) < 0.0) L.push_back(i);
		else if (A.at(i).at(0) == 0.0) N.push_back(i);
		else U.push_back(i); 
	}
	std::vector<std::vector<double>> new_A {};
	std::vector<double> new_b {};
	std::vector<std::vector<double>> C {};
	for (auto i : L){
		for (auto j : U){
			//The rows i and j form a pair of upper/lower bound
			// Now we have to generate the new inequality
			std::vector<double> new_row {};
			std::vector<double> coefficient_row(As.last().size(), 0.0);
			for (int k=0; k!=As.last().at(i).size(); ++k){
				new_row.push_back(A.at(i).at(k)/A.at(i).at(0) + A.at(j).at(k)/A.at(j).at(0));
				coefficient_row[i]=1/A.at(i).at(0);
				coefficient_row[j]=1/A.at(j).at(0);
			}
			new_A.push_back(new_row);
			new_b.push_back(b[i]/A[i][0] + b[j]/A[j][0]);
			C.push_back(coefficient_row);
		}
	}
	for (auto i : N){
		//Copy the inequalities where x_1 doesn't occur
	}
	As.push_back(new_A);
	bs.push_back(new_b);
	Coeffs.push_back(C);
}

/* Outline for Fourier-Motzkin elimination

create lists/vectors of A's, b's and coefficient matrices C
while(As.last().at(1).size() >1){
	A_new, b_new, C_new = FourierMotzkinStep(As.last(), bs.last())
	append A_new, b_new, C_new to respective list
}
//Check if there exists a solution, if not, remember the first wrong inequality 
int no_solution_at {As.last().size()}; //correct syntax?
for (int i=0, i!=As.last().size(), ++i){
	if (As.last().at(1).at(i) > bs.last().at(i)){
		no_solution_at=i;
		break;
	}
}
if (no_solution_at == As.last().size()){
	//Calculate a solution
}
else{
	//Calculate the certificate
}
*/

/* Old main function
int main()
{	
	std::vector<std::vector<double>> A{
	{1,3.5,2},
	{4,2,1.6},
	{5.3,7,1},
	{4.4,7,3},
	{2.5,3,1}
	};
	std::cout << to_str(A);
}
*/

int main(int argc, const char *argv[])
{
	if (argc < 2){
		std::cerr << "Usage: " << argv[0] << " <lp filename> /n";
		return EXIT_FAILURE;
	}
	int success;
	success = read_LP(argv[1]);
	std::cout << "I read the following problem:\n";
	std::cout << to_str(bs.at(0));
	std::cout << "\n";
	std::cout << to_str(As.at(0));
}
